version: '3.9'

networks:
  test-network:
    driver: bridge

services:
  niffler-all-db:
    container_name: niffler-all-db
    image: postgres:15.1
    environment:
      - POSTGRES_MULTIPLE_DATABASES="niffler-auth","niffler-currency","niffler-spend","niffler-userdata"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "5432"
    networks:
      - test-network
    dns_search: .

  auth.niffler.dc:
    container_name: auth.niffler.dc
    image: dtuchs/niffler-auth:latest
    ports:
      - "9001:9001"
    healthcheck:
      test: "wget --spider http://localhost:9001/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  currency.niffler.dc:
    container_name: currency.niffler.dc
    image: dtuchs/niffler-currency:latest
    expose:
      - "8091"
      - "8092"
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  gateway.niffler.dc:
    container_name: gateway.niffler.dc
    image: dtuchs/niffler-gateway:latest
    ports:
      - "8090:8090"
    depends_on:
      auth.niffler.dc:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  spend.niffler.dc:
    container_name: spend.niffler.dc
    image: dtuchs/niffler-spend:latest
    expose:
      - "8093"
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  #ИМАДЖ ВАЕРМОК ДЛЯ РЕСТА
  userdata.niffler.dc:
    container_name: userdata.niffler.dc
    image: wiremock/wiremock:2.35.0
    ports:
      - "8089:8089"
      - "9000:9000"
    #      по дефолту мок работает через порт 8080, ниже переопределяем
    command: ["--port", "8089"]
    #    указываем в каком пакете внутри докера будет храниться наш маппинг
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - test-network
    dns_search: .

  frontend.niffler.dc:
    container_name: frontend.niffler.dc
    image: dtuchs/niffler-frontend-test:latest
    ports:
      - "80:80"
    depends_on:
      gateway.niffler.dc:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.10.12
    platform: "${ARCH}"
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "3", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "niffler-st2_test-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.9
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "9090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network
    dns_search: .

  niffler-e-2-e:
    container_name: niffler-e-2-e
    image: dtuchs/niffler-e-2-e-tests
    depends_on:
      frontend.niffler.dc:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  allure:
    container_name: allure
    image: frankescobar/allure-docker-service
    depends_on:
      - niffler-e-2-e
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 0
    ports:
      - "5050:5050"
    networks:
      - test-network
    dns_search: .
