version: '3.9'

services:
  niffler-all-db:
    container_name: niffler-all-db
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - niffler-network
    dns_search: .

  auth.niffler.dc:
    container_name: auth.niffler.dc
    image: dtuchs/niffler-auth:latest
    ports:
      - "9001:9001"
    healthcheck:
      test: "wget --spider http://localhost:9001/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network
    dns_search: .

  currency.niffler.dc:
    container_name: currency.niffler.dc
    image: dtuchs/niffler-currency:latest
    expose:
      - "8091"
      - "8092"
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network
    dns_search: .

  gateway.niffler.dc:
    container_name: gateway.niffler.dc
    image: dtuchs/niffler-gateway:latest
    ports:
      - "8090:8090"
    healthcheck:
      test: "wget --spider http://localhost:8090/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      - auth.niffler.dc
    networks:
      - niffler-network
    dns_search: .

  spend.niffler.dc:
    container_name: spend.niffler.dc
    image: dtuchs/niffler-spend:latest
    expose:
      - "8093"
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network
    dns_search: .

  userdata.niffler.dc:
    container_name: userdata.niffler.dc
    image: dtuchs/niffler-userdata:latest
    expose:
      - "8089"
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network
    dns_search: .

  frontend.niffler.dc:
    container_name: frontend.niffler.dc
    image: dtuchs/niffler-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      gateway.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network
    dns_search: .

volumes:
  pgdata:
    external: true

networks:
  niffler-network:
    driver: bridge
